services:
  database:
    image : postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ../database/db-data:/var/lib/postgresql/data
      - ../database/config/:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=animal_scanner
    networks:
      - animal-explorer

  backend:
    image: animal-scanner-backend:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./config/config.ini:/animal-scanner-backend.config.ini
    networks:
      - animal-explorer
    depends_on:
      - database

networks:
    animal-explorer:
        driver: bridge
        name: animal-explorer-module
